### ISSUE TITLE
Bypass certificate

### ISSUE THREAD

**Issue by AdamorfuX** [lamarios/unifi-throughput-ncurses#2]
Hi
Is there any way to bypass the certificate error?
cannot validate certificate for "IP" because it doesn't contain any IP SANs

**Comment by lamarios** [comment]
I'm having an issue building one of the dependency and I raised an issue on the library git repo so it might take some time.

**Comment by lamarios** [comment]
New release done (1.5), I currently don't have a raspberry pi running on hands so I only built for x86 and ncurses 6. If you don't meet those requirements you'll have to build it yourself.

To skip SSL certificate verification add

bypassSsl = true

to your config file.
